services:
  - type: web
    name: gamerverse
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client  # Updated path
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
